# Generated by Django 4.2.8 on 2023-12-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('salary', models.PositiveIntegerField()),
                ('skills', models.TextField()),
                ('duty', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
